apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: aero-sensor-broker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: config-volume
          mountPath: /settings
          readOnly: true
        - name: dev-volume
          mountPath: /dev
        - name: run-udev-volume
          mountPath: /run/udev
        resources:
          limits:
            akri.sh/akri-udev: "1"
          requests:
            akri.sh/akri-udev: "1"
        env:
        - name: CLUSTER_DISPLAY_NAME
          value: {{ .Values.location }}
        ports:
          - containerPort: 3030
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3030
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3030
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config-volume
        secret:
          secretName: influxdb-aero-sensor-config
      - name: dev-volume
        hostPath:
          path: /dev
          type: Directory
      - name: run-udev-volume
        hostPath:
          path: /run/udev
          type: Directory
